actors:
  yamagata:
    image_url: /images/actors/bob.png
    name: yamagata
    url: http://sns.example.com/bob
  tachibana:
    image_url: /images/actors/alice.png
    name: tachibana
    url: http://sns.example.com/alice
author: harusamecast
description: 春雨Castは東京でWebエンジニアをしている2人が気になっているトピックについてお互いに質問していくポッドキャストです
description_long: 春雨Castは東京でWebエンジニアをしている2人が気になっているトピックについてお互いに質問していくポッドキャストです
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: G-W56Z6JXJVP
hashtag: harusamecast
itunes_podcast_url:
keywords: エンジニア,ポッドキャスト,Ojisan
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 春雨Cast
url: https://harusamecast.github.io/
